"""Remove nullable attribute from note_date_time in Favourite model

Revision ID: 254d2a5f372c
Revises: 9521647b844b
Create Date: 2024-06-08 19:22:47.004696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254d2a5f372c'
down_revision: Union[str, None] = '9521647b844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favourites', 'note_date_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favourites', 'note_date_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
