"""Add note column to Favourite table

Revision ID: 57a07d8bcbab
Revises: e606f6648125
Create Date: 2024-06-05 12:54:54.162544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a07d8bcbab'
down_revision: Union[str, None] = 'e606f6648125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites', 'note')
    # ### end Alembic commands ###
