"""Add DateTime column in Favourite model

Revision ID: 9521647b844b
Revises: 57a07d8bcbab
Create Date: 2024-06-08 19:03:38.665619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9521647b844b'
down_revision: Union[str, None] = '57a07d8bcbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites', sa.Column('note_date_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites', 'note_date_time')
    # ### end Alembic commands ###
